name: "Terraform CI - Análisis"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_analysis:
    name: "Validar Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: ETAPA 1 - TFLint
        run: |
          tflint --init
          tflint

      - name: ETAPA 2 - Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: true

      - name: Terraform Init
        run: terraform init -backend=false

      - name: ETAPA 3 - Terraform Validate
        run: terraform validate
